name: Build iOS IPA

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Xcode
              run: sudo xcode-select -switch /Applications/Xcode.app

            - name: Build and archive
              run: |
                  xcodebuild clean archive \
                    -project PakePlus.xcodeproj \
                    -scheme PakePlus \
                    -configuration Release \
                    -sdk iphoneos \
                    -archivePath ${{ github.workspace }}/build/PakePlus.xcarchive \
                    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO DEVELOPMENT_TEAM=""

            - name: Create ExportOptions.plist
              run: |
                  cat > ExportOptions.plist <<EOF
                  <?xml version="1.0" encoding="UTF-8"?>
                  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
                  <plist version="1.0">
                  <dict>
                      <key>method</key>
                      <string>release-testing</string>
                      <key>signingStyle</key>
                      <string>none</string>
                      <key>teamID</key>
                      <string></string>
                      <key>compileBitcode</key>
                      <false/>
                      <key>destination</key>
                      <string>export</string>
                      <key>stripSwiftSymbols</key>
                      <true/>
                      <key>signingCertificate</key>
                      <string>Apple Development</string>
                      <key>provisioningProfiles</key>
                      <dict/>
                  </dict>
                  </plist>
                  EOF

            - name: Export IPA
              run: |
                  ls -l ExportOptions.plist
                  cat ExportOptions.plist
                  xcodebuild -exportArchive \
                    -archivePath ${{ github.workspace }}/build/PakePlus.xcarchive \
                    -exportOptionsPlist ExportOptions.plist \
                    -exportPath ${{ github.workspace }}/build \
                    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO DEVELOPMENT_TEAM=""

            - name: Upload IPA
              uses: actions/upload-artifact@v3
              with:
                  name: PakePlus.ipa
                  path: ${{ github.workspace }}/build/PakePlus.ipa
