name: Build IPA

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Xcode
              uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: '16.2.0'

            - name: Install Dependencies (Homebrew & Theos)
              run: |
                  echo "Installing Homebrew..."
                  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

                  echo "Setting up Homebrew..."
                  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
                  eval "$(/opt/homebrew/bin/brew shellenv)"

                  echo "Installing ImageMagick for App Icon resizing..."
                  brew install imagemagick

                  echo "Installing Theos dependencies..."
                  brew install ldid dpkg

                  echo "Cloning Theos..."
                  git clone --recursive https://github.com/theos/theos.git $HOME/theos
                  echo 'export THEOS=$HOME/theos' >> $HOME/.zshrc
                  export THEOS=$HOME/theos

            - name: Generate and Set App Icon
              run: |
                  # 创建 Assets.xcassets 目录结构
                  mkdir -p Assets.xcassets/AppIcon.appiconset

                  # 使用 ImageMagick 生成多尺寸图标
                  convert appicon.png -resize 20x20 Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@1x.png
                  convert appicon.png -resize 40x40 Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@2x.png
                  convert appicon.png -resize 60x60 Assets.xcassets/AppIcon.appiconset/AppIcon-20x20@3x.png
                  convert appicon.png -resize 29x29 Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@1x.png
                  convert appicon.png -resize 58x58 Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@2x.png
                  convert appicon.png -resize 87x87 Assets.xcassets/AppIcon.appiconset/AppIcon-29x29@3x.png
                  convert appicon.png -resize 40x40 Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@1x.png
                  convert appicon.png -resize 80x80 Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@2x.png
                  convert appicon.png -resize 120x120 Assets.xcassets/AppIcon.appiconset/AppIcon-40x40@3x.png
                  convert appicon.png -resize 60x60 Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@1x.png
                  convert appicon.png -resize 120x120 Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@2x.png
                  convert appicon.png -resize 180x180 Assets.xcassets/AppIcon.appiconset/AppIcon-60x60@3x.png
                  convert appicon.png -resize 76x76 Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@1x.png
                  convert appicon.png -resize 152x152 Assets.xcassets/AppIcon.appiconset/AppIcon-76x76@2x.png
                  convert appicon.png -resize 167x167 Assets.xcassets/AppIcon.appiconset/AppIcon-83.5x83.5@2x.png
                  convert appicon.png -resize 1024x1024 Assets.xcassets/AppIcon.appiconset/AppIcon-1024x1024@1x.png

                  # 生成 Contents.json 配置文件
                  cat > Assets.xcassets/AppIcon.appiconset/Contents.json <<EOL
                  {
                    "images": [
                      {
                        "size": "20x20",
                        "idiom": "iphone",
                        "filename": "AppIcon-20x20@1x.png",
                        "scale": "1x"
                      },
                      {
                        "size": "20x20",
                        "idiom": "iphone",
                        "filename": "AppIcon-20x20@2x.png",
                        "scale": "2x"
                      },
                      {
                        "size": "20x20",
                        "idiom": "iphone",
                        "filename": "AppIcon-20x20@3x.png",
                        "scale": "3x"
                      },
                      {
                        "size": "29x29",
                        "idiom": "iphone",
                        "filename": "AppIcon-29x29@1x.png",
                        "scale": "1x"
                      },
                      {
                        "size": "29x29",
                        "idiom": "iphone",
                        "filename": "AppIcon-29x29@2x.png",
                        "scale": "2x"
                      },
                      {
                        "size": "29x29",
                        "idiom": "iphone",
                        "filename": "AppIcon-29x29@3x.png",
                        "scale": "3x"
                      },
                      {
                        "size": "40x40",
                        "idiom": "iphone",
                        "filename": "AppIcon-40x40@1x.png",
                        "scale": "1x"
                      },
                      {
                        "size": "40x40",
                        "idiom": "iphone",
                        "filename": "AppIcon-40x40@2x.png",
                        "scale": "2x"
                      },
                      {
                        "size": "40x40",
                        "idiom": "iphone",
                        "filename": "AppIcon-40x40@3x.png",
                        "scale": "3x"
                      },
                      {
                        "size": "60x60",
                        "idiom": "iphone",
                        "filename": "AppIcon-60x60@1x.png",
                        "scale": "1x"
                      },
                      {
                        "size": "60x60",
                        "idiom": "iphone",
                        "filename": "AppIcon-60x60@2x.png",
                        "scale": "2x"
                      },
                      {
                        "size": "60x60",
                        "idiom": "iphone",
                        "filename": "AppIcon-60x60@3x.png",
                        "scale": "3x"
                      },
                      {
                        "size": "76x76",
                        "idiom": "ipad",
                        "filename": "AppIcon-76x76@1x.png",
                        "scale": "1x"
                      },
                      {
                        "size": "76x76",
                        "idiom": "ipad",
                        "filename": "AppIcon-76x76@2x.png",
                        "scale": "2x"
                      },
                      {
                        "size": "83.5x83.5",
                        "idiom": "ipad",
                        "filename": "AppIcon-83.5x83.5@2x.png",
                        "scale": "2x"
                      },
                      {
                        "size": "1024x1024",
                        "idiom": "ios-marketing",
                        "filename": "AppIcon-1024x1024@1x.png",
                        "scale": "1x"
                      }
                    ],
                    "info": {
                      "version": 1,
                      "author": "xcode"
                    }
                  }
                  EOL

                  echo "✅ App Icon 已生成并配置完成！"

            - name: Build IPA Package
              run: |
                  export THEOS=$HOME/theos
                  echo "Building IPA package..."
                  make package FINALPACKAGE=1 PACKAGE_FORMAT=ipa

            - name: Get IPA File Path
              id: find_ipa
              run: |
                  IPA_PATH=$(find ./packages -name "*.ipa" | head -n 1)
                  echo "IPA File: $IPA_PATH"
                  echo "ipa_path=$IPA_PATH" >> $GITHUB_ENV

            - name: Upload IPA to GitHub Releases
              uses: softprops/action-gh-release@v2
              with:
                  files: ${{ env.ipa_path }}
                  tag_name: 'pakeplus-v1.0.0'
                  body: 'pakeplus-v1.0.0'
                  draft: false
                  prerelease: false
                  publish: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
