name: Build and Export Un-Signed IPA

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Ruby
              uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '2.7'

            - name: Install dependencies
              run: bundle install

            - name: Set up Xcode
              uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: '16.2.0'

            - name: Build the app
              run: xcodebuild clean build -workspace PakePlus.xcworkspace -scheme PakePlus -configuration Release -sdk iphoneos -derivedDataPath build

            - name: Create an unsigned IPA
              run: |
                  mkdir -p output
                  xcodebuild -exportArchive -archivePath build/Build/Products/Release-iphoneos/PakePlus.xcarchive -exportPath output -exportOptionsPlist ExportOptions.plist

            - name: Upload IPA
              uses: actions/upload-artifact@v2
              with:
                  name: unsigned-ipa
                  path: output/*.ipa
