name: Build and Archive SwiftUI App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: macos-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Xcode
              uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: '16.2.0'

            - name: Resolve Swift Packages
              run: xcodebuild -resolvePackageDependencies -project PakePlus.xcodeproj -scheme PakePlus

            - name: Build and archive
              run: |
                  xcodebuild clean archive \
                    -project PakePlus.xcodeproj \
                    -scheme PakePlus \
                    -configuration Release \
                    -sdk iphoneos \
                    -archivePath ${{ github.workspace }}/build/PakePlus.xcarchive \
                    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

            - name: Create ExportOptions.plist
              run: |
                  cat > ExportOptions.plist <<EOF
                  {
                      "method": "none",
                      "signingStyle": "manual",
                      "compileBitcode": false,
                      "destination": "export",
                      "stripSwiftSymbols": true
                  }
                  EOF

            - name: Export IPA
              run: |
                  xcodebuild -exportArchive \
                    -archivePath ${{ github.workspace }}/build/PakePlus.xcarchive \
                    -exportOptionsPlist ExportOptions.plist \
                    -exportPath ${{ github.workspace }}/build

            - name: Upload IPA to GitHub Releases
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ github.workspace }}/build/PakePlus.ipa
                  asset_name: PakePlus.ipa
                  asset_content_type: application/octet-stream
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
